# Generated by Django 3.2.7 on 2021-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0011_rename_mobile_no_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='item',
            table='sam_item',
        ),
    ]
