# Generated by Django 3.2.7 on 2021-09-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0012_auto_20210929_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
