# Generated by Django 3.2.7 on 2021-09-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0014_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='sam_customer',
        ),
    ]
